config/routes.rb
Hydracamp::Application.routes.draw do

  devise_for :archivists

  match "zombies/search" => "zombies#search", :as => 'search_zombies'
  match 'zombies/:id/history' => "zombies#history", :as => 'zombie_history'
  resources :zombies

  resources :tweets

  root :to => 'zombies#index'

end

app/models/archivist.rb
class Archivist < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model

  attr_accessible :email, :password, :password_confirmation, :remember_me, :points

  after_initialize :init

  def level
    case points 
      when nil
        self.points = 100
        self.save!
        "Flesh Apprentice"
      when 0..150
        "Flesh Apprentice"
      when 151..250
        "Cadaver Expert"
      when 251..1000
        "Cranium Master"
      end
  end
  
  def inc_points(num)
    self.points += num
    self.save!
  end
    
protected
        
  def init
    self.points ||= 100
  end

  # attr_accessible :title, :body

end

app/models/datastreams/zombie_eac_cpf.rb
class ZombieEacCpf < ActiveFedora::NokogiriDatastream

  set_terminology do |t|
    t.root(:path=>'eac-cpf', :xmlns=>'urn:isbn:1-931666-33-4')
    t.name(:path=>"cpfDescription/oxns:identity/oxns:nameEntry/oxns:part")
    # t.creator(:path=>"...")  
    # t.nickname(:path=>"...")
    # t.description_of_life(:path=>"...")
    # t.description_of_undeath(:path=>"...")
    # t.graveyard(:path=>"...")
    # t.weapon(:path=>"...")
    # t.date_of_birth(:path=>"...")
    # t.date_of_death(:path=>"...")
    # t.date_of_undeath(:path=>"...")
  end
  
  # Template is loaded from lib/zombie-default.eac-cpf.xml
  def self.xml_template
    Nokogiri::XML::Document.parse(File.new(File.join(File.dirname(__FILE__),'..', 'lib', "zombie-default.eac-cpf.xml")))
  end
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :zombie
  attr_accessible :message, :deleted_at, :rating
  validates :zombie, :presence=>true  
  acts_as_paranoid
end

app/models/zombie.rb
class NicknameValidator < ActiveModel::Validator
  def validate(record)
    if (record.nickname =~ /[^hrungoa]/i )
      record.errors[:nickname] << "Nickname contains invalid characters"
    end
  end
end

class Zombie < ActiveRecord::Base
  attr_accessible :graveyard, :name, :nickname, :level, :date_of_birth, :date_of_death, :date_of_undeath,
  		:hit_points, :description, :active, :wins, :losses, :creator_id, :weapon, :avatar
  audited

  validates :name, :presence=>true, :uniqueness=>true
  validates_with NicknameValidator
  validates :active, :presence=>true
  validates :wins, :presence=>true
  validates :losses, :presence=>true
  validates :weapon, :presence=>true

  has_many :tweets, :dependent => :destroy
  belongs_to :creator, :class_name=>'Zombie'

  after_initialize :init

  # Add zombie avatar (via paperclip library)
  has_attached_file :avatar, :styles => { medium: "300x300>", thumb: "100x100>" }, :default_url => '/assets/missing_:style.png'

  def init
    self.hit_points ||= 100
    self.level ||= 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # create
  def create
    zombie_id = params[:tweet].delete(:zombie_id)
    @tweet = Tweet.new(params[:tweet])
    @tweet.zombie_id = zombie_id
    @tweet.save!
    current_archivist.inc_points 25
    redirect_to zombie_path(@tweet.zombie), :notice=>"Tweet Added"
  end
  
  def update
    tweet = Tweet.find(params[:id])
    tweet.rating += 1
    tweet.save!
    redirect_to zombie_path(tweet.zombie), :notice=>"Tweet Liked"
  end

  def index
    @tweets = Tweet.where("").order(:created_at).reverse_order
  end
  
  def destroy
    coin = rand(2)
    if coin == 1
      @tweet = Tweet.destroy(params[:id])
    else
      @tweet = Tweet.find(params[:id])
      @tweet = @tweet.update_attributes(:message => @tweet.message.split.shuffle.join(" "))
    end
    redirect_to tweets_path, :notice=>"The Tweet is gone, or is it..."
  end
  
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  def new
    @zombie = Zombie.new
  end
  
  def destroy    
    Zombie.destroy(params[:id])
    redirect_to zombies_path
  end

  def create
    @zombie = Zombie.create(params[:zombie])
    @zombie.avatar = params[:zombie][:avatar] if params[:zombie][:avatar].present? rescue nil
    @zombie.save!
    current_archivist.inc_points 50
    redirect_to zombies_path, :notice=>"Added Zombie"
  end

  def index
    @zombies = Zombie.order(:name)
  end

  def show
    @zombie = Zombie.find(params[:id])
    @tweets = @zombie.tweets
    @tweet = Tweet.new
    @tweet.zombie = @zombie
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @zombie }
      format.xml  { render xml: @zombie }
    end
  end

  def edit
    @zombie = Zombie.find(params[:id])
  end

  def update
    @zombie = Zombie.find(params[:id])
    @zombie.update_attributes(params[:zombie])
    @zombie.avatar = params[:zombie][:avatar] if params[:zombie][:avatar].present? rescue nil
    @zombie.save!
    redirect_to edit_zombie_path(@zombie), :notice=>"Zombie saved at #{Time.now.strftime("%H:%M")}"
  end

  def search
    @q = params[:q]

    q_delimited_by_space = @q.split(' ')

    generated_like_clause = []
    args = []
    q_delimited_by_space.each do |word|
      generated_like_clause << "name LIKE ? OR nickname LIKE ? OR description LIKE ? OR graveyard LIKE ?"
      args << "%#{word}%" << "%#{word}%" << "%#{word}%" << "%#{word}%"
    end

    #Convert generated_like_clause from array to string, using ' OR ' delimiter
    generated_like_clause = generated_like_clause.join(' OR ')

    @zombies = Zombie.where(generated_like_clause, *args )
  end

  def history
    @zombie = Zombie.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/globals/_flash_messages.html.erb
<% if flash[:alert].present? %> 
<div class="alert alert-error">
  <%= flash[:alert] %>
</div>
<% end %>

<% if flash[:notice].present? %>
<div class="alert">
  <%= flash[:notice] %>
</div>
<% end %>

app/views/globals/_navigation.html.erb
<ul class="nav nav-pills">
  <li><%= link_to 'Home', zombies_path %>
	  <li><%= link_to 'Tweets', tweets_path %>
  <li><%= link_to 'Instructional Video', 'http://www.youtube.com/watch?v=0UqEhUm2B_8', {:target => "_blank" } %>
  <li class="pull-right">
    <%= form_tag(search_zombies_path, :method => "get", :class => 'form-inline') do %>
    <%= text_field_tag(:q, nil, :placeholder => 'Find a zombie...') %>
    <%= submit_tag("Search Zombies", :class => 'btn') %>
  </li>
  <% end %>
</ul>

app/views/globals/_user_management.html.erb
<div id="user_management" class="pull-right">
  Welcome <%= current_archivist ? current_archivist.email : 'stranger' %> 
  <% if current_archivist %>
    ( <%= current_archivist.level %> | <%= current_archivist.points %> )
    <%= button_to 'Log out', destroy_archivist_session_path, method: :delete %>
  <% else %>
    <%= link_to 'Log in', new_archivist_session_path %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Archivists v. Zombies beta</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>

<!-- HEADER -->
<div class="row span12">
  <h1 class="pull-left"><i class="icon-fire"></i> Twitter ... for Zombie Archivists <i class="icon-fire"></i></h1><%= image_tag 'zombie_logo.gif', :class => 'pull-right', :width=> '50' %>
</div>
<!-- MAIN BODY -->
<div class="row span12">
  <%= render partial: 'globals/navigation' %>
  <!-- User navigation -->
  <%= render partial: 'globals/user_management' %>

  <!-- Page heading -->
  <div class="span12">
    <h2><%= yield :title || 'Twitter ... for Zombie Archivists' %></h2>
  </div>

  <!-- Content container -->
  <div class="span12" id="content_body">
    <%= render partial: 'globals/flash_messages' %>
    <%= yield %>
  </div>
</div>

<!-- FOOTER -->
<div class="span12" id="footer">
  &copy; ZombieCo 2012
</div>
</body>
</html>

app/views/tweets/index.html.erb
<table class="table table-striped">
	<tr>
	<td id="zombie_name">Zombie</td>
	<td id="zombie_tweet">Said ...</td>
    </tr>
	<%- @tweets.each do |tweet| %>
	<tr>
	  <td class="tweet"><%= link_to tweet.zombie.name, zombie_path(tweet.zombie) %></td>
      <td class="tweet"><%= tweet.message %></td>
	  <td class="tweet"><%= link_to "delete", tweet_path(tweet), :method => :delete %>
    </tr>
  <% end %>
</table>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/zombies/edit.html.erb
<h1>Edit Zombie</h1>

<%= form_for @zombie do |f| %>
  <p>
    <%=f.label :name %>
    <%=f.text_field :name %>
  </p>
  <p>
    <%=f.label :graveyard %>
    <%=f.text_field :graveyard %>
  </p>
  <p>
    <%=f.label :nickname %>
    <%=f.text_field :nickname %>
    <span id="nickname_error" class="error">Nicknames can only contain these characters: a g h n r o u !</span>
  </p>
  <p>
    <%=f.label :description %>
    <%=f.text_field :description %>
  </p>
<p>
  <%=f.label :date_of_birth %>
  <%=f.date_select :date_of_birth, :start_year => 1500 %>
</p>
<p>
  <%=f.label :date_of_death %>
  <%=f.date_select :date_of_death %>
</p>
<p>
  <%=f.label :date_of_undeath %>
  <%=f.date_select :date_of_undeath %>
</p>

<p>
  <%=f.label :creator %>
  <%= select_tag(:creator, options_for_select([""]+Zombie.order(:name).reject{|z| z==@zombie}.map{|z| z.name})) %>
</p>
  <p>
    <%=f.label :creator_id %>
    <%=f.select(:creator_id, options_for_select(["",""]+ Zombie.order(:name).reject{|z| z==@zombie}.map{|z| [ z.name, z.id ]}, @zombie.creator_id)) %>
  </p>



 <p>

  <%=f.label :weapon %>
  <%=f.text_field :weapon %>
</p>

    <div class="zombieCreateRow">
      <%= f.label :avatar %>
      <div class="field">
        <% if @zombie.avatar? %>
            <%= image_tag @zombie.avatar.url(:thumb) %>
        <% end %>
        <%= f.file_field :avatar %>
        <span class="label label-important">JPG, GIF, or PNG (less than 2MB)</span>
      </div>
    </div>

  <p><%=f.submit %></p>

<% end %>

<p><%=link_to "View Zombie", zombie_path(@zombie)%></p>
<p><%= link_to "home", zombies_path %></p>

app/views/zombies/history.html.erb
<h1>History for Zombie <%= @zombie.name %></h1>


<table>
  <tr>
    <th>Action</th>
    <th>Changes</th>
  </tr>
<%- @zombie.audits.each do |audit| %>
  <tr>
    <td><%= audit.action %></td>
    <td><%= audit.audited_changes %></td>
  </tr>
<%- end %>
</table>

app/views/zombies/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <td>Zombie</td>
      <td>Nickname</td>
      <td>Level</td>
      <td>Description</td>
      <td>&nbsp;</td>
    </tr>
  </thead>

  <tbody>
    <% @zombies.each do |zombie| %>

      <tr data-zombie="<%= zombie.id %>">
        <td class="zombie_name"><%= link_to zombie.name, zombie_path(zombie) %></td>
        <td class="zombie_nickname"><%= zombie.nickname%></td>
        <td class="zombie_level"><%= zombie.level.to_s %></td>
        <td class="zombie_description"><%= zombie.description %></td>
        <td class="zombie_edit"><%= link_to "Edit", edit_zombie_path(zombie) %></td>
        <td>
          <%= link_to "Delete", zombie_path(zombie), :method => "delete" %>
        </td>
      </tr>
    <% end %>
  </tbody>

</table>

<%= link_to "Create New Zombie", new_zombie_path, class: 'btn' %>

app/views/zombies/new.html.erb
<h1>Create a new Zombie</h1>
<%= form_for @zombie do |f| %>
  <%=f.label :name %>
  <%=f.text_field :name %>
  <br />
  <%=f.label :graveyard %>
  <%=f.text_field :graveyard %>
  
  <br />
  <%=f.label :description %>
  <%=f.text_field :description %>
  <br />

    <div class="zombieCreateRow">
      <%= f.label :avatar %>
      <div class="field">
        <%= f.file_field :avatar %>
        <span class="label label-important">JPG, GIF, or PNG (less than 2MB)</span>
      </div>
    </div>

  <br>
  <%=f.label :nickname %>
  <%=f.text_field :nickname %>
  <span id="nickname_error" class="error">Nicknames can only contain these characters: a g h n r o u !</span>
  <br>
  <br>
  <%=f.label :date_of_birth %>
  <%=f.date_select :date_of_birth, :start_year => 1500 %>
  <br>
  <%=f.label :date_of_death %>
  <%=f.date_select :date_of_death %>
  <br>
  <%=f.label :date_of_undeath %>
  <%=f.date_select :date_of_undeath %>
  <br>

<br>
  <%=f.label :weapon %>
  <%=f.text_field :weapon %>

  <%=f.submit %>
<%end%>

app/views/zombies/search.html.erb
<h3>Zombie Search Deluxe</h3>

<div><strong>Searching names, nicknames, descriptions and graveyards for:</strong> <%= @q %></div>
<br />
<% if @zombies.nil? || @zombies.empty? %>
  No zombies found.
<% else %>

  <table class="table table-bordered">
    <thead>
      <tr>
        <td>Zombie</td>
        <td>Nickname</td>
        <td>Description</td>
        <td>Actions</td>
      </tr>
    </thead>

    <tbody>
      <% @zombies.each do |zombie| %>
      <tr data-zombie="<%= zombie.id %>">
        <td class="zombie_name"><%= link_to zombie.name, zombie_path(zombie) %></td>
        <td class="zombie_nickname"><%= zombie.nickname%></td>
        <td class="zombie_description"><%= zombie.description %></td>
        <td class="zombie_edit"><%= link_to "Edit", edit_zombie_path(zombie) %></td>
      </tr>
    <% end %>
  </table>

<% end %>

app/views/zombies/show.html.erb
<h1>Show Zombie</h1>
<dl id="zombie_details">
  <dt>Name:</dt>
  <dd><%= @zombie.name %></dd>
  <dt>Level:</dd>
  <dd>level <%= @zombie.level %></dd>
  <dt>Graveyard:</dt>
  <dd><%= @zombie.graveyard %></dd>
  <dt>Description:</dt>
  <dd><%= @zombie.description %></dd>
  <dt>Nickname:</dt>
  <dd><%= @zombie.nickname %></dd>
  <% if @zombie.date_of_birth != nil%>
  <dt>Date of Birth:</dt>
  <dd><%= @zombie.date_of_birth.strftime("%B %e, %Y") %></dd>
  <% end %>
  <% if @zombie.date_of_death != nil%>
  <dt>Date of Death:</dt>
  <dd><%= @zombie.date_of_death.strftime("%B %e, %Y") %></dd>
  <% end %>
  <% if @zombie.date_of_undeath != nil%>
  <dt>Date of Undeath:</dt>
  <dd><%= @zombie.date_of_undeath.strftime("%B %e, %Y") %></dd>
  <% end %>
  <dt>Active:</dt>
  <dd><%= @zombie.active.to_s %></dd>
  <dt>Number of Tweets:</dt>
  <dd><%= @zombie.tweets.count %></dd>
</dl>

<h2 id="zombie_name"><%= @zombie.name %> <%= link_to 'Edit', edit_zombie_path(@zombie) %></h2>
<table class="table table-striped" id="zombie_details">
  <tbody>
    <tr>
      <td>Avatar</td>
      <td><%= image_tag @zombie.avatar.url(:medium) %></td>
    </tr>
    <tr>
      <td>Level</td>
      <td><%= @zombie.level %></td>
    </tr>
    <tr>
      <td>Graveyard</td>
      <td><%= @zombie.graveyard %></td>
    </tr>
    <tr>
      <td>Nickname</td>
      <td><%= @zombie.nickname %></td>
    </tr>
    <tr>
      <td>Date of death</td>
      <td><%= @zombie.date_of_death.blank? ? '-' : @zombie.date_of_death.strftime("%B %e, %Y") %></td>
    </tr>
    <tr>
      <td>Active</td>
      <td><%= @zombie.active? ? 'Yes' : 'No' %></td>
    </tr>
    <tr>
      <td>Description</td>
      <td><%= @zombie.description %></td>
    </tr>
  </tbody>
</table>
<%= link_to "edit", edit_zombie_path(@zombie) %>
<%= link_to "history", zombie_history_path(@zombie) %>


<h2 id="tweets">Tweets (<%= @zombie.tweets.count %>)</h2>
<%= form_for @tweet do |f| %>
  <%= f.hidden_field :zombie_id %>
  <%= f.text_field :message %>
  <%= f.submit "Add Tweet" %>
<% end %>

<table class="table table-striped" id="zombie_tweets">
  <thead>
    <tr>
      <td>&nbsp;</td>
      <td>Rating</td>
      <td>&nbsp;</td>
    </tr>
  </thead>
  <tbody>
  <% @zombie.tweets.each do |tweet| %>
    <tr id="tweet_<%= tweet.id %>">
      <td class="message"><%= tweet.message %> (<%= tweet.created_at.strftime("%B %e, %Y") %>)</td>
      <td class="like_count"><%= tweet.rating %></td>
      <td class="like_update">
        <%= form_for tweet do |f| %>
          <%= hidden_field_tag 'id', tweet.id %>
          <%= f.submit 'Like' %>
        <% end %>
    </tr>
  <% end %>
  </tbody>
</table>